substitutions:
  description:
    none: none
    template: '{subs_used}{plus_gk_on_bench}-of-{subs_named}{stops}{extra_time}{free_gk}'
    plus_gk_on_bench: '+GK'
    free_gk_sub_allowed: '+GK'
    stops_one: ' (in {count} stoppage max)'
    stops_other: ' (in {count} stoppages max)'
    extra_time: '+{count}-extra-time'