substitutions:
  description:
    none: keine
    template: '{subs_used}{plus_gk_on_bench} von {subs_named}{stops}{extra_time}{free_gk}'
    plus_gk_on_bench: '+GK'
    free_gk_sub_allowed: '+GK'
    stops_one: ' (max. {count} Unterbrechung)'
    stops_other: ' (max. {count} Unterbrechungen)'
    extra_time: '+{count} Verl.'