substitutions:
  description:
    none: brak
    template: '{subs_used}{plus_gk_on_bench} z {subs_named}{stops}{extra_time}{free_gk}'
    plus_gk_on_bench: '+GK'
    free_gk_sub_allowed: '+GK'
    stops_one: ' (maks. {count} przerwa)'
    stops_other: ' (maks. {count} przerwy)'
    extra_time: '+{count} dogr.'