substitutions:
  description:
    none: 없음
    template: '{subs_named}명 중 {subs_used}명{plus_gk_on_bench}{stops}{extra_time}{free_gk}'
    plus_gk_on_bench: '+GK'
    free_gk_sub_allowed: '+GK'
    stops_one: ' (중단 {count}회까지)'
    stops_other: ' (중단 {count}회까지)'
    extra_time: '+연장 {count}명'