substitutions:
  description:
    none: nenhuma
    template: '{subs_used}{plus_gk_on_bench} de {subs_named}{stops}{extra_time}{free_gk}'
    plus_gk_on_bench: '+GK'
    free_gk_sub_allowed: '+GK'
    stops_one: ' (máx. {count} paragem)'
    stops_other: ' (máx. {count} paragens)'
    extra_time: '+{count} prolong.'